sudo: false

language: c

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libnotify-dev

before_script:
  - autoreconf --install && mkdir build && cd build

script:
  - ../configure --enable-libnotify && make
